exclude: '^(\.tox|\.circleci|\.bumpversion\.cfg|.templates)(/|$)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: name-tests-test
{%- if cookiecutter.dependency_manager != "poetry" %}
      - id: requirements-txt-fixer
{% endif %}
{%- if cookiecutter.allow_commit_to_main != "yes" %}
      - id: no-commit-to-branch
{% endif %}

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        name: format code with black
        files: ^notebooks/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.0
    hooks:
      - id: isort
        name: sort imports with isort
        args: ["--profile", "black"]
        files: ^notebooks/

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: lint with flake8
        pass_filenames: false
        files: ^notebooks/

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.0
    hooks:
      - id: nbstripout

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.0
    hooks:
      - id: nbqa-black # Run 'black' on Jupyter Notebooks
        files: notebooks/
      - id: nbqa-isort # Run 'isort' on Jupyter Notebooks
        files: notebooks/
        args: ["--float-to-top"]

